# Generated by Django 4.0.2 on 2022-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_speciality', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
            ],
        ),
    ]
